### ISSUE TITLE
twitterwebapi 

### ISSUE THREAD

**Issue by thierryd31** [debsahu/TwitterWebAPI#4]
Hi, 

good work for your api twitter, but how see the twitter return code status : 200, 403, 402, .... 

Thanks !

**Comment by debsahu** [comment]
You can check for error code returned by twitter here: https://github.com/debsahu/TwitterWebAPI/blob/310d63c30ba29736109888500362d5a22e148ec2/TwitterWebAPI.h#L1015

Docs for working with clients is here: https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/client-examples.html#test-it-live

**Comment by thierryd31** [comment]
Yes thanks , i found it ! and now return response code
